### ISSUE TITLE
global: naming consistency

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-deposit#44]
Should we consider changing some of the names in the module while it's still easy:

- ``invenio-deposit`` -> ``invenio-deposits`` (plus all instances of module name usage in directory structures, config).
- ``_deposit`` -> ``_internal`` (deposit-specific stuff in JSON metadata)
- ``pid_type='dep'`` -> ``pid_type='depid'`` (*invenio_deposit/config.py*)

**Comment by lnielsen** [comment]
cc @tiborsimko

**Comment by jirikuncar** [comment]
> - ``invenio-deposit`` -> ``invenio-deposits`` (plus all instances of module name usage in directory structures, config).

We have already released old version on PyPI under `invenio-deposit`.

> - ``_deposit`` -> ``_internal`` (deposit-specific stuff in JSON metadata)

IMHO it's better if each module manages it's own "key". Do you suggest to change also Invenio-Collections and Invenio-OAIServer?

> - ``pid_type='dep'`` -> ``pid_type='depid'`` (*invenio_deposit/config.py*)

👍

**Comment by tiborsimko** [comment]
Yes, `invenio-deposits` would be the proper name according to our naming conventions:

-  http://invenio.readthedocs.io/en/latest/architecture/module-anatomy-naming.html

OT1H, it would be good to do this change to keep things overall consistent. OTOH, since we already released the package under `invenio-deposit` name, we'd have to think about deprecating it etc etc, which is probably not worth the time trouble in these pre-release sprint times...

**Comment by lnielsen** [comment]
@JavierDelgadoFernandez I've assigned it to you - the change is just the the last part - i.e.:

> ``pid_type='dep'`` -> ``pid_type='depid'`` (invenio_deposit/config.py)
